version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - backend
      - redis
      - db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reinventdb
    ports:
      - "5432:5432"
