version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the project directory for hot-reloading
    ports:
      - "8000:8000"  # Map localhost:8000 to the container's port 8000
    environment:
      - ENV_FILE=.env  # Load environment variables from .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reinvent
    ports:
      - "5432:5432"  # Expose PostgreSQL to localhost

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis to localhost
