version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reinventdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d reinventdb"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Sync FastAPI backend code
      - ./reinvent:/app/reinvent  # ✅ Ensure Celery can write configs/results
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    env_file:
      - .env
    command: ["celery", "-A", "src.tasks.molecule_task", "worker", "--loglevel=debug", "--queues=molecule"]
    privileged: true  # ✅ Allows Celery worker to run Docker commands
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ Mount Docker socket for access
      - ./reinvent:/app/reinvent  # ✅ Ensure Celery can write configs/results
      - ./reinvent/configs:/app/reinvent/configs  # ✅ Ensures REINVENT sees the configs

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  reinvent:
    build:
      context: .
      dockerfile: Dockerfile.reinvent
    volumes:
      - ./reinvent:/app/reinvent  # Share REINVENT folder
      - ./reinvent/tasks:/app/reinvent/tasks  

    command: sleep infinity  # ✅ Keep container running to inspect files
