
run_type = "transfer_learning"
device = "cpu"

[parameters]
model_file = "priors/reinvent.prior"
input_smiles_path = "/app/projects/33bd261b-e51f-42d8-b200-52acb36e51e8/input/train.csv"
output_model_path = "/app/projects/33bd261b-e51f-42d8-b200-52acb36e51e8/models/agent.pt"
num_epochs = 10
batch_size = 128
max_steps = 1000
