
run_type = "sampling"
device = "cpu"
json_out_config = "/app/projects/4100f125-40fa-4e79-b351-1b7db373721f/runs/run_b3a59d7fb3d54c1bad05b90ad1cfb86e/sampling.json"

[parameters]
model_file = "/app/projects/4100f125-40fa-4e79-b351-1b7db373721f/models/agent.pt"
output_file = "/app/projects/4100f125-40fa-4e79-b351-1b7db373721f/runs/run_b3a59d7fb3d54c1bad05b90ad1cfb86e/raw_results.csv"
num_smiles = 128
unique_molecules = true
randomize_smiles = true
